=== brpocock/jmonkeyengine/data/XML docs/LoaderFormat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by john (john) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Scene">
		<xs:annotation>
			<xs:documentation>Begining of the file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Model" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Group of meshes making up a drawable thing</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Mesh" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Basicly a TriMesh</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Color" type="FloatList"/>
										<xs:element name="Index" type="IntList"/>
										<xs:element name="Normal" type="FloatList"/>
										<xs:element name="TextureCoords" type="FloatList"/>
										<xs:element name="Vertex" type="FloatList"/>
										<xs:group ref="RenderState" minOccurs="0" maxOccurs="unbounded"/>
										<xs:group ref="Controller" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attributeGroup ref="WorldRef"/>
									<xs:attributeGroup ref="Basics"/>
								</xs:complexType>
							</xs:element>
							<xs:group ref="Controller" minOccurs="0" maxOccurs="unbounded"/>
							<xs:group ref="RenderState" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attributeGroup ref="WorldRef"/>
						<xs:attributeGroup ref="Basics"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SysEffects" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>System wide effects</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="Basics"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="Basics">
		<xs:annotation>
			<xs:documentation>Allows name and flags</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="flags" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<xs:simpleType name="FloatList">
		<xs:annotation>
			<xs:documentation>A list of floats</xs:documentation>
		</xs:annotation>
		<xs:list itemType="xs:float"/>
	</xs:simpleType>
	<xs:simpleType name="IntList">
		<xs:annotation>
			<xs:documentation>A list of integers</xs:documentation>
		</xs:annotation>
		<xs:list itemType="xs:int"/>
	</xs:simpleType>
	<xs:attributeGroup name="WorldRef">
		<xs:annotation>
			<xs:documentation>Allows worldly refrences</xs:documentation>
		</xs:annotation>
		<xs:attribute name="translation" use="optional" default="0 0 0">
			<xs:simpleType>
				<xs:restriction base="FloatList">
					<xs:minLength value="3"/>
					<xs:maxLength value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rotation" use="optional" default="0 0 0 0">
			<xs:simpleType>
				<xs:restriction base="FloatList">
					<xs:minLength value="4"/>
					<xs:maxLength value="4"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="scale" use="optional" default="1">
			<xs:simpleType>
				<xs:restriction base="xs:float">
					<xs:minExclusive value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:simpleType name="ColorRGBA">
		<xs:annotation>
			<xs:documentation>Color information</xs:documentation>
		</xs:annotation>
		<xs:list itemType="xs:float"/>
	</xs:simpleType>
	<xs:group name="Controller">
		<xs:choice>
			<xs:element name="JointAnimation"/>
			<xs:element name="KeyframeAnimation"/>
		</xs:choice>
	</xs:group>
	<xs:group name="RenderState">
		<xs:annotation>
			<xs:documentation>Renderable States</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="TextureState">
				<xs:complexType/>
			</xs:element>
			<xs:group ref="Light"/>
		</xs:choice>
	</xs:group>
	<xs:complexType name="BaseLightType">
		<xs:attribute name="AmbientColor" type="ColorRGBA" use="optional" default="0 0 0 0"/>
		<xs:attribute name="SpecularColor" type="ColorRGBA" use="optional" default="0 0 0 0"/>
	</xs:complexType>
	<xs:group name="Light">
		<xs:choice>
			<xs:element name="DirectionalLight" type="BaseLightType"/>
			<xs:element name="PointLight" type="BaseLightType"/>
		</xs:choice>
	</xs:group>
</xs:schema>

=== brpocock/jmonkeyengine/data/XML docs/SampleXMLScene.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample scene to load-->
<Scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LoaderFormat.xsd">
	<Model name="Human">
		<Mesh name="Head">
			<MaterialState emissive="0 0 0 1" alpha="1" ambient="0 0 0 1" diffuse="0 1 0 1" shiny="64" specular="1 1 1 1"/>
			<Vertex>
            0 0 0 1 0 0 0 1 0 </Vertex>
			<Normal>0 0 1 0 0 1 0 0 1</Normal>
			<Color>1 0 0 1 0 1 0 1 0 0 0 1 </Color>
			<TextureCoords/>
			<Index> 0 1 2
            </Index>
		</Mesh>
		<Primative type="Box" params="MyBox -1 -1 -1 1 1 1" translation="7 7 7"/>
	</Model>
</Scene>
